sudo: required
services:
- docker
env:
  global:
    # Ensure the downloaded SDK is first on the PATH
    - PATH=${HOME}/google-cloud-sdk/bin:$PATH
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- mkdir javascriptsdk
- mv !(javascriptsdk) javascriptsdk
- mv javascriptsdk/javascriptcredentials.tar.enc javascriptcredentials.tar.enc
- openssl aes-256-cbc -K $encrypted_008ab571332e_key -iv $encrypted_008ab571332e_iv -in javascriptcredentials.tar.enc -out javascriptcredentials.tar -d
- git clone https://github.com/cloudboost/cloudboost
- tar -xvf javascriptcredentials.tar
- rm javascriptcredentials.tar
- rm gc_cred.json
- mkdir cloudboost/config
- mv smtp.json cloudboost/config/smtp.json
- docker run --name mongo -p 27017:27017 -d mongo:3.2 
- docker run --name redis -p 6379:6379 -d redis:3.0 
- sleep 30s
- docker exec $(docker ps -aqf "name=mongo") mongo _GLOBAL --eval "db.getCollection('_Settings').insertOne({secureKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',clusterKey:'1227d1c4-1385-4d5f-ae73-23e99f74b006',myURL:'http://localhost:4730'});"
- mv javascriptsdk cloudboost/javascriptsdk
install:
- cd cloudboost/javascriptsdk
- npm install
- cd ..
- docker build -t cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/cloudboost:latest .
- docker run --name cloudboost -p 4730:4730 -it --link redis:redis --link mongo:mongo -d cloudboost/cloudboost:2.0.$TRAVIS_BUILD_NUMBER 
- sleep 30s
- cd javascriptsdk
- npm test
- cd ..
after_success:
#Deploy. 
#Docker Login
- cd ..
- openssl aes-256-cbc -K $encrypted_008ab571332e_key -iv $encrypted_008ab571332e_iv -in javascriptcredentials.tar.enc -out javascriptcredentials.tar -d
- tar -xvf javascriptcredentials.tar
- docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL
# Make sure SDK is downloaded - cache once it's working
- curl https://sdk.cloud.google.com | bash;
# List the SDK contents to ensure it's downloaded
- ls -l ${HOME}/google-cloud-sdk/bin
# Ensure the correct gcloud is being used
- which gcloud
# Print the gcloud version and make sure it's something
- gcloud --version
- ls
#Activate Google Cloud SDK with your project
- gcloud auth activate-service-account --key-file gc_cred.json
#Install Kubectl
- gcloud components install kubectl
- gcloud container clusters get-credentials $GOOGLECLUSTERNAME --zone $GOOGLEZONE --project $GOOGLEPROJECT
#Push docker images. 
- docker push cloudboost/cloudboost:latest
#Upload to Kubernetes for deployment.
- kubectl rolling-update cloudboost-engine --image=cloudboost/cloudboost:latest
- rm javascriptcredentials.tar
- mv cloudboost/javascriptsdk javascriptsdk
- rm -rf cloudboost
- cd javascriptsdk
- mv * ../
- cd ..
- rm javascriptsdk
deploy:
  provider: npm
  api_key: $NPMKey
  email: $NPMEmail
#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW

